name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: 18.x
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        id: node
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

  frontend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Frontend type-check
        run: npm --workspace frontend run type-check
      - name: Frontend lint
        run: npm --workspace frontend run lint
      - name: Frontend test
        run: npm --workspace frontend run test

  backend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Backend type-check
        run: npm --workspace backend run type-check
      - name: Backend lint
        run: npm --workspace backend run lint
      - name: Backend test
        run: npm --workspace backend run test
